import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { applyStructuralFix, isStructuralViolation } from "@/lib/fix-engine";
import type { AxeViolation } from "@/lib/scan-types";

export interface HealRequest {
    violation: AxeViolation;
    nodeHtml: string; // ONLY the specific broken snippet from axe-core (violation.nodes[n].html)
}

export interface HealResponse {
    original: string;
    fixed: string;
    strategy: "jsdom" | "gemini";
    description: string;
}

// ─── Gemini semantic fix ──────────────────────────────────────────────────────

async function applyGeminifix(
    violation: AxeViolation,
    nodeHtml: string
): Promise<HealResponse> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        throw new Error("GEMINI_API_KEY is not set in environment variables.");
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    // Use the original gemini-pro model which is guaranteed to work on older SDKs
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    // ── Hard cap: never send more than 500 chars of HTML to Gemini ──────────
    // Axe-core sometimes reports violations on root <html>/<body> nodes whose
    // .html snapshot is the entire page. Truncating prevents 429 quota errors.
    const MAX_SNIPPET_CHARS = 500;
    const safeSnippet =
        nodeHtml.length > MAX_SNIPPET_CHARS
            ? nodeHtml.slice(0, MAX_SNIPPET_CHARS) + "\n...[content truncated]..."
            : nodeHtml;

    const prompt = `You are an expert web accessibility engineer fixing WCAG 2.1 AA violations.

VIOLATION
Rule: ${violation.id}
Description: ${violation.help}
WCAG Tags: ${violation.tags.filter((t) => t.startsWith("wcag")).join(", ")}

BROKEN HTML SNIPPET
${safeSnippet}

TASK
Fix ONLY the broken HTML snippet above to resolve the accessibility violation.

STRICT OUTPUT RULES:
- Output ONLY the corrected raw HTML snippet — nothing else
- No markdown, no code fences, no backticks, no explanatory text
- Keep all existing attributes and content; only add/modify what fixes the violation
- For missing alt text: write a concise, descriptive alt based on element context
- For missing aria-label: write a clear, human-readable label
- Output must be valid HTML that drops in as a direct replacement`;

    const result = await model.generateContent(prompt);
    const fixedHtml = result.response.text().trim();

    return {
        original: nodeHtml,
        fixed: fixedHtml,
        strategy: "gemini",
        description: `Semantic fix generated by Gemini AI for rule: ${violation.id}`,
    };
}

// ─── Route Handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
    let body: Partial<HealRequest>;
    try {
        body = await req.json();
    } catch {
        return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const { violation, nodeHtml } = body;

    if (!violation || !nodeHtml) {
        return NextResponse.json(
            { error: "Missing required fields: violation, nodeHtml" },
            { status: 400 }
        );
    }

    try {
        // ── Hybrid Fix Engine Decision ────────────────────────────────────────────
        // Check if this violation has a deterministic structural fix first.
        // Only call Gemini AI for violations requiring semantic text generation.

        const hasDeterministicFix = isStructuralViolation(violation.id);

        if (hasDeterministicFix) {
            const jsdomResult = applyStructuralFix(violation.id, nodeHtml);
            if (jsdomResult) {
                // Deterministic fix succeeded
                const response: HealResponse = {
                    original: nodeHtml,
                    fixed: jsdomResult.fixedHtml,
                    strategy: "jsdom",
                    description: jsdomResult.description,
                };
                return NextResponse.json(response);
            }
            // jsdomResult was null → fixer explicitly delegated to Gemini (e.g. image-alt)
        }

        // ── Gemini AI semantic fix ────────────────────────────────────────────────
        const geminiResult = await applyGeminifix(violation, nodeHtml);
        return NextResponse.json(geminiResult);

    } catch (err) {
        console.error("[AllyFlow heal error]", err);
        const message = err instanceof Error ? err.message : "Unknown error";
        return NextResponse.json(
            { error: `Heal failed: ${message}` },
            { status: 500 }
        );
    }
}
