import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { applyStructuralFix, isStructuralViolation } from "@/lib/fix-engine";
import type { AxeViolation } from "@/lib/scan-types";

export interface HealRequest {
    violation: AxeViolation;
    nodeHtml: string; // ONLY the specific broken snippet from axe-core (violation.nodes[n].html)
}

export interface HealResponse {
    original: string;
    fixed: string;
    strategy: "jsdom" | "gemini";
    description: string;
}

// ─── Image Fetcher for Multimodal AI ──────────────────────────────────────────

async function fetchImageAsBase64(url: string) {
    try {
        // We can only fetch absolute URLs (starting with http)
        if (!url.startsWith('http')) {
            console.warn(`[AllyFlow] Cannot fetch relative image URL: ${url}`);
            return null;
        }

        const response = await fetch(url);
        if (!response.ok) return null;

        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const mimeType = response.headers.get('content-type') || 'image/jpeg';

        return {
            inlineData: {
                data: buffer.toString('base64'),
                mimeType
            }
        };
    } catch (e) {
        console.warn(`[AllyFlow] Multimodal fetch failed for: ${url}`);
        return null; // If fetch fails, we gracefully degrade to text-only mode
    }
}

// ─── Gemini semantic fix ──────────────────────────────────────────────────────

// app/api/heal/route.ts

// ─── Gemini semantic fix (UPGRADED WITH FALLBACK) ─────────────────────────────



// ─── Gemini semantic fix (Day 2: Multimodal + Fallback) ──────────────────────

async function applyGeminifix(
    violation: AxeViolation,
    nodeHtml: string
): Promise<HealResponse> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        throw new Error("GEMINI_API_KEY is not set in environment variables.");
    }

    const genAI = new GoogleGenerativeAI(apiKey);

    const MAX_SNIPPET_CHARS = 500;
    const safeSnippet =
        nodeHtml.length > MAX_SNIPPET_CHARS
            ? nodeHtml.slice(0, MAX_SNIPPET_CHARS) + "\n...[content truncated]..."
            : nodeHtml;

    const promptText = `You are an expert web accessibility engineer fixing WCAG 2.1 AA violations.

VIOLATION
Rule: ${violation.id}
Description: ${violation.help}

BROKEN HTML SNIPPET
${safeSnippet}

TASK
Fix ONLY the broken HTML snippet above to resolve the accessibility violation.

STRICT OUTPUT RULES:
- Output ONLY the corrected raw HTML snippet — nothing else
- No markdown, no explanatory text
- If an image is provided, write a highly descriptive, visually accurate 'alt' attribute based on what you actually see in the image.
- Output must be valid HTML that drops in as a direct replacement`;

    // ── Day 2: Image Extraction Logic ─────────────────────────────────────────
    let imagePart = null;

    // If the violation is related to image alt text, look for an image source
    if (violation.id === 'image-alt') {
        const srcMatch = nodeHtml.match(/src=["'](.*?)["']/);
        if (srcMatch && srcMatch[1]) {
            console.log(`[AllyFlow] Image detected. Fetching for multimodal analysis: ${srcMatch[1]}`);
            imagePart = await fetchImageAsBase64(srcMatch[1]);
        }
    }

    // Bundle the prompt. If we have an image, send both text AND image!
    const contentParts = imagePart ? [promptText, imagePart] : [promptText];

    try {
        console.log(`[AllyFlow] Attempting gemini-2.5-flash for rule: ${violation.id}`);
        const primaryModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const result = await primaryModel.generateContent(contentParts);
        const fixedHtml = result.response.text().trim();

        return {
            original: nodeHtml,
            fixed: fixedHtml,
            strategy: "gemini",
            description: `Semantic multimodal fix generated by Gemini 2.5 Flash for rule: ${violation.id}`,
        };

    } catch (error: any) {
        if (error.status === 503 || error.status === 429) {
            console.warn(`[AllyFlow] Flash model busy (Status ${error.status}). Falling back to flash-lite...`);
            await new Promise(resolve => setTimeout(resolve, 500));

            try {
                const fallbackModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
                const fallbackResult = await fallbackModel.generateContent(contentParts);
                const fallbackFixedHtml = fallbackResult.response.text().trim();

                return {
                    original: nodeHtml,
                    fixed: fallbackFixedHtml,
                    strategy: "gemini",
                    description: `Semantic multimodal fix generated by Gemini 2.5 Flash-Lite (Fallback) for rule: ${violation.id}`,
                };
            } catch (fallbackError: any) {
                throw new Error("AI models are currently overloaded. Please try again in a few seconds.");
            }
        }
        throw error;
    }
}
// ─── Route Handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
    let body: Partial<HealRequest>;
    try {
        body = await req.json();
    } catch {
        return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const { violation, nodeHtml } = body;

    if (!violation || !nodeHtml) {
        return NextResponse.json(
            { error: "Missing required fields: violation, nodeHtml" },
            { status: 400 }
        );
    }

    try {
        // ── Hybrid Fix Engine Decision ────────────────────────────────────────────
        // Check if this violation has a deterministic structural fix first.
        // Only call Gemini AI for violations requiring semantic text generation.

        const hasDeterministicFix = isStructuralViolation(violation.id);

        if (hasDeterministicFix) {
            const jsdomResult = applyStructuralFix(violation.id, nodeHtml);
            if (jsdomResult) {
                // Deterministic fix succeeded
                const response: HealResponse = {
                    original: nodeHtml,
                    fixed: jsdomResult.fixedHtml,
                    strategy: "jsdom",
                    description: jsdomResult.description,
                };
                return NextResponse.json(response);
            }
            // jsdomResult was null → fixer explicitly delegated to Gemini (e.g. image-alt)
        }

        // ── Gemini AI semantic fix ────────────────────────────────────────────────
        const geminiResult = await applyGeminifix(violation, nodeHtml);
        return NextResponse.json(geminiResult);

    } catch (err) {
        console.error("[AllyFlow heal error]", err);
        const message = err instanceof Error ? err.message : "Unknown error";
        return NextResponse.json(
            { error: `Heal failed: ${message}` },
            { status: 500 }
        );
    }
}