import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import type { AxeViolation } from "@/lib/scan-types";

export interface HealRequest {
    violation: AxeViolation;
    nodeHtml: string;
}

export interface HealResponse {
    original: string;
    fixed: string;
    strategy: "jsdom" | "gemini";
    description: string;
}

async function fetchImageAsBase64(url: string) {
    try {
        if (!url.startsWith('http')) return null;
        const response = await fetch(url);
        if (!response.ok) return null;
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const mimeType = response.headers.get('content-type') || 'image/jpeg';
        return { inlineData: { data: buffer.toString('base64'), mimeType } };
    } catch (e) {
        return null;
    }
}

async function applyGeminifix(violation: AxeViolation, nodeHtml: string): Promise<HealResponse> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY is not set.");

    const genAI = new GoogleGenerativeAI(apiKey);
    const MAX_SNIPPET_CHARS = 500;
    const safeSnippet = nodeHtml.length > MAX_SNIPPET_CHARS ? nodeHtml.slice(0, MAX_SNIPPET_CHARS) + "\n...[content truncated]..." : nodeHtml;

    // ── NEW: AGGRESSIVE, STRICT PROMPT ──
    const promptText = `You are a ruthless, expert web accessibility engineer fixing WCAG 2.1 AA violations. 
You MUST MODIFY the HTML to fix the issue. NEVER RETURN THE EXACT SAME CODE.

VIOLATION
Rule: ${violation.id}
Description: ${violation.help}

BROKEN HTML SNIPPET
${safeSnippet}

TASK & STRICT OUTPUT RULES:
1. Fix the broken HTML snippet above to resolve the violation. 
2. YOU MUST CHANGE THE CODE. If it is a contrast issue, change the CSS hex codes to pass WCAG 4.5:1 (e.g., #333333 or #000000).
3. If it is a fake button (like an <a> without href or a <div>), YOU MUST add href="#", role="button", and tabindex="0", or change the tag entirely to <button>.
4. If adding an aria-label or alt text, make it highly descriptive of the element's actual purpose (e.g., "Email Address" not "Content region").
5. Output ONLY the corrected raw HTML snippet. No markdown, no backticks, no explanations.
6. MUST be valid HTML.`;

    let imagePart = null;
    if (violation.id === 'image-alt') {
        const srcMatch = nodeHtml.match(/src=["'](.*?)["']/);
        if (srcMatch && srcMatch[1]) {
            imagePart = await fetchImageAsBase64(srcMatch[1]);
        }
    }

    const contentParts = imagePart ? [promptText, imagePart] : [promptText];

    try {
        const primaryModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const result = await primaryModel.generateContent(contentParts);
        // Clean markdown backticks just in case the AI ignores instructions
        const fixedHtml = result.response.text().replace(/^```html\s*|^```\s*/g, '').replace(/```$/g, '').trim();

        return {
            original: nodeHtml,
            fixed: fixedHtml,
            strategy: "gemini",
            description: `Aggressive semantic fix generated by Gemini 2.5 Flash for rule: ${violation.id}`,
        };
    } catch (error: any) {
        if (error.status === 503 || error.status === 429) {
            await new Promise(resolve => setTimeout(resolve, 500));
            try {
                const fallbackModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
                const fallbackResult = await fallbackModel.generateContent(contentParts);
                const fallbackFixedHtml = fallbackResult.response.text().replace(/^```html\s*|^```\s*/g, '').replace(/```$/g, '').trim();

                return { original: nodeHtml, fixed: fallbackFixedHtml, strategy: "gemini", description: `Fallback fix for: ${violation.id}` };
            } catch (fallbackError: any) {
                throw new Error("AI models are currently overloaded.");
            }
        }
        throw error;
    }
}

export async function POST(req: NextRequest) {
    let body: Partial<HealRequest>;
    try {
        body = await req.json();
    } catch {
        return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const { violation, nodeHtml } = body;
    if (!violation || !nodeHtml) return NextResponse.json({ error: "Missing required fields" }, { status: 400 });

    try {
        // ── NEW: BYPASS JSDOM FIXER ──
        // We are forcing everything to Gemini so it can make smart, contextual decisions
        const geminiResult = await applyGeminifix(violation, nodeHtml);
        return NextResponse.json(geminiResult);
    } catch (err) {
        const message = err instanceof Error ? err.message : "Unknown error";
        return NextResponse.json({ error: `Heal failed: ${message}` }, { status: 500 });
    }
}